# NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
# If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
#
# - name: Setup Gradle
#   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
#   with:
#     gradle-version: '8.9'
#
# - name: Build with Gradle 8.9
#   run: gradle build

name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/OhMuseCake-Backend
            git pull origin main
            ./gradlew build -x test
            sudo cp build/libs/ohmusecake-0.0.1-SNAPSHOT.jar /opt/ohmusecake/app.jar
            sudo systemctl restart ohmusecake